### ISSUE TITLE
There was a problem with your code: TypeError: text.bold is not a function

### ISSUE THREAD

**Issue by MushroomMaula** [bmo-at/vscode-sosml#3] opened 2020-11-14 12:43 UTC
Currently I get this error (`There was a problem with your code: TypeError: text.bold is not a function `) everytime I try to run any program. It seems to be resulting from https://github.com/bmo-at/vscode-sosml/blob/a4cd473fa75ca6a2e26498c38dbcd2dcf058f06e/src/webview.ts#L20 this line of code. It seems like `String.prototype.bold` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/bold), this is also the case for `String.prototype.italics`.
I'm using VSCode version `1.51.1` on windows

**Comment by bmo-at** [comment] 2020-11-14 17:55
I am also on 1.51.1, I can't reproduce it. Can you provide more details?

**Comment by MushroomMaula** [comment] 2020-11-14 19:24
Actually i'm not really sure why I get this error and this is everything it says

**Comment by bmo-at** [comment] 2020-12-03 00:27
I usually don't like to fix bugs that I can't reproduce and have no proper reports of. Exception made, fixed in version 1.3.0 by 81ff75c3a065da4e54c06a4fd6411681f7964a46

**Closed** 2020-12-03 00:27 UTC
